// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfja7HaqPG5vpr57nBiAosYkVwX6dbTE',
    appId: '1:689305562868:web:3ffa8f885d37f4966978a1',
    messagingSenderId: '689305562868',
    projectId: 'holbegram-724f2',
    authDomain: 'holbegram-724f2.firebaseapp.com',
    databaseURL: 'https://holbegram-724f2-default-rtdb.firebaseio.com',
    storageBucket: 'holbegram-724f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPwoLqrhH4DZ63DPPBZQ7PmdltRM9dKpI',
    appId: '1:689305562868:android:67c97f25e2b277b96978a1',
    messagingSenderId: '689305562868',
    projectId: 'holbegram-724f2',
    databaseURL: 'https://holbegram-724f2-default-rtdb.firebaseio.com',
    storageBucket: 'holbegram-724f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjpuIB3xCaViqMbqVgXaAHmyya2_7Js0',
    appId: '1:689305562868:ios:89816e480e9b63da6978a1',
    messagingSenderId: '689305562868',
    projectId: 'holbegram-724f2',
    databaseURL: 'https://holbegram-724f2-default-rtdb.firebaseio.com',
    storageBucket: 'holbegram-724f2.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfjpuIB3xCaViqMbqVgXaAHmyya2_7Js0',
    appId: '1:689305562868:ios:ce4cf838840d50046978a1',
    messagingSenderId: '689305562868',
    projectId: 'holbegram-724f2',
    databaseURL: 'https://holbegram-724f2-default-rtdb.firebaseio.com',
    storageBucket: 'holbegram-724f2.appspot.com',
    iosBundleId: 'com.example.holbegram.RunnerTests',
  );
}
